export const API_ENDPOINTS = {
    EXAM: '/api/core/Exam',
    EXAM_BY_ID: (id: string) => `/api/core/Exam/${id}`,
    EXAM_ROUTINE: (examId: string) => `/api/core/Exam/${examId}/routine`,
    EXAM_ROUTINE_BY_ID: (id: string) => `/api/core/Exam/routine/${id}`,
    EXAM_ROUTINE_SESSION: (routineId: string) => `/api/core/Exam/routine/${routineId}/session`,
    EXAM_SESSION_BY_ID: (id: string) => `/api/core/Exam/session/${id}`,
    EXAM_SESSION_RESCHEDULE: (sessionId: string) => `/api/core/Exam/session/${sessionId}/reschedule`,
    EXAM_ROUTINE_SHIFT: (routineId: string, daysToShift: number) => `/api/core/Exam/routine/${routineId}/shift/${daysToShift}`,
    EXAM_ROUTINE_REORDER: (routineId: string) => `/api/core/Exam/routine/${routineId}/reorder`,
    INSTITUTE_CLASS: '/api/core/InstituteClass',
    INSTITUTE_CLASS_BY_ID: (id: string) => `/api/core/InstituteClass/${id}`,
    RESULT: '/api/core/Result',
    RESULT_BY_ID: (id: string) => `/api/core/Result/${id}`,
    STUDENT_CREATE: '/api/core/Student/create',
    STUDENT_GET: (id: string) => `/api/core/Student/get/${id}`,
    STUDENT_UPDATE: (id: string) => `/api/core/Student/update/${id}`,
    STUDENT_GET_ALL: '/api/core/Student/get-all',
    STUDENT_REPORT: (resultId: string) => `/api/core/StudentReport/${resultId}`,
    STUDENT_REPORT_BY_ID: (id: string) => `/api/core/StudentReport/${id}`,
    STUDENT_REPORT_SINGLE: (id: string) => `/api/core/StudentReport/report-single/${id}`,
    STUDENT_REPORT_ALL_RESULT: (resultId: string) => `/api/core/StudentReport/report-all-result/${resultId}`,
    SUBJECT: '/api/core/Subject',
    SUBJECT_BY_ID: (id: string) => `/api/core/Subject/${id}`,
    TEACHER_CREATE: '/api/core/Teacher/create',
    TEACHER_GET: (id: string) => `/api/core/Teacher/get/${id}`,
    TEACHER_UPDATE: (id: string) => `/api/core/Teacher/update/${id}`,
    TEACHER_GET_ALL: '/api/core/Teacher/get-all',
    USER_LOGIN: '/api/User/login',
    USER_REGISTER: '/api/User/register',
    USER_REGISTER_ADMIN: '/api/User/register-admin',
};
